name: shinnamon
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  onesignal_flutter: ^3.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  google_fonts: 2.2.0
  http: ^0.13.3
  provider: ^6.0.2
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  url_launcher: ^6.0.10
  whatsapp_unilink: ^2.0.0
  image_picker: 0.8.4
  image: ^3.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
